+define+TEST_MACRO
+incdir+../rtl
../rtl/test_designs/riscv-master/core/riscv/riscv_core.v
../rtl/test_designs/riscv-master/core/riscv/riscv_alu.v
../rtl/test_designs/riscv-master/core/riscv/riscv_csr.v
../rtl/test_designs/riscv-master/core/riscv/riscv_csr_regfile.v
../rtl/test_designs/riscv-master/core/riscv/riscv_decode.v
../rtl/test_designs/riscv-master/core/riscv/riscv_decoder.v
../rtl/test_designs/riscv-master/core/riscv/riscv_defs.v
../rtl/test_designs/riscv-master/core/riscv/riscv_divider.v
../rtl/test_designs/riscv-master/core/riscv/riscv_exec.v
../rtl/test_designs/riscv-master/core/riscv/riscv_fetch.v
../rtl/test_designs/riscv-master/core/riscv/riscv_issue.v
../rtl/test_designs/riscv-master/core/riscv/riscv_lsu.v
../rtl/test_designs/riscv-master/core/riscv/riscv_mmu.v
../rtl/test_designs/riscv-master/core/riscv/riscv_multiplier.v
../rtl/test_designs/riscv-master/core/riscv/riscv_pipe_ctrl.v
../rtl/test_designs/riscv-master/core/riscv/riscv_regfile.v
../rtl/test_designs/riscv-master/core/riscv/riscv_trace_sim.v
../rtl/test_designs/riscv-master/core/riscv/riscv_xilinx_2r1w.v

